// Code generated by MockGen. DO NOT EDIT.
// Source: hall.go
//
// Generated by this command:
//
//	mockgen -source=hall.go -destination=../mocks/hall_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "cinema-service/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHallRepository is a mock of HallRepository interface.
type MockHallRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHallRepositoryMockRecorder
	isgomock struct{}
}

// MockHallRepositoryMockRecorder is the mock recorder for MockHallRepository.
type MockHallRepositoryMockRecorder struct {
	mock *MockHallRepository
}

// NewMockHallRepository creates a new mock instance.
func NewMockHallRepository(ctrl *gomock.Controller) *MockHallRepository {
	mock := &MockHallRepository{ctrl: ctrl}
	mock.recorder = &MockHallRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHallRepository) EXPECT() *MockHallRepositoryMockRecorder {
	return m.recorder
}

// CreateHall mocks base method.
func (m *MockHallRepository) CreateHall(body models.Hall) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHall", body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHall indicates an expected call of CreateHall.
func (mr *MockHallRepositoryMockRecorder) CreateHall(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHall", reflect.TypeOf((*MockHallRepository)(nil).CreateHall), body)
}

// DeleteHallByID mocks base method.
func (m *MockHallRepository) DeleteHallByID(id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHallByID", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteHallByID indicates an expected call of DeleteHallByID.
func (mr *MockHallRepositoryMockRecorder) DeleteHallByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHallByID", reflect.TypeOf((*MockHallRepository)(nil).DeleteHallByID), id)
}

// GetAllHalls mocks base method.
func (m *MockHallRepository) GetAllHalls() ([]models.Hall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHalls")
	ret0, _ := ret[0].([]models.Hall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHalls indicates an expected call of GetAllHalls.
func (mr *MockHallRepositoryMockRecorder) GetAllHalls() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHalls", reflect.TypeOf((*MockHallRepository)(nil).GetAllHalls))
}

// GetHallByID mocks base method.
func (m *MockHallRepository) GetHallByID(id int) (models.Hall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHallByID", id)
	ret0, _ := ret[0].(models.Hall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHallByID indicates an expected call of GetHallByID.
func (mr *MockHallRepositoryMockRecorder) GetHallByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHallByID", reflect.TypeOf((*MockHallRepository)(nil).GetHallByID), id)
}

// UpdateHall mocks base method.
func (m *MockHallRepository) UpdateHall(id int, body models.Hall) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHall", id, body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHall indicates an expected call of UpdateHall.
func (mr *MockHallRepositoryMockRecorder) UpdateHall(id, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHall", reflect.TypeOf((*MockHallRepository)(nil).UpdateHall), id, body)
}
