// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "cinema-service/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckIsAdmin mocks base method.
func (m *MockRepository) CheckIsAdmin(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIsAdmin", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckIsAdmin indicates an expected call of CheckIsAdmin.
func (mr *MockRepositoryMockRecorder) CheckIsAdmin(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsAdmin", reflect.TypeOf((*MockRepository)(nil).CheckIsAdmin), id)
}

// CreateHall mocks base method.
func (m *MockRepository) CreateHall(body models.Hall) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHall", body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHall indicates an expected call of CreateHall.
func (mr *MockRepositoryMockRecorder) CreateHall(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHall", reflect.TypeOf((*MockRepository)(nil).CreateHall), body)
}

// CreateMovie mocks base method.
func (m *MockRepository) CreateMovie(body models.Movie) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMovie", body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMovie indicates an expected call of CreateMovie.
func (mr *MockRepositoryMockRecorder) CreateMovie(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMovie", reflect.TypeOf((*MockRepository)(nil).CreateMovie), body)
}

// CreateSession mocks base method.
func (m *MockRepository) CreateSession(session models.Session) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", session)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockRepositoryMockRecorder) CreateSession(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockRepository)(nil).CreateSession), session)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), user)
}

// DeleteHallByID mocks base method.
func (m *MockRepository) DeleteHallByID(id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHallByID", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteHallByID indicates an expected call of DeleteHallByID.
func (mr *MockRepositoryMockRecorder) DeleteHallByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHallByID", reflect.TypeOf((*MockRepository)(nil).DeleteHallByID), id)
}

// DeleteMovieByID mocks base method.
func (m *MockRepository) DeleteMovieByID(id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMovieByID", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMovieByID indicates an expected call of DeleteMovieByID.
func (mr *MockRepositoryMockRecorder) DeleteMovieByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMovieByID", reflect.TypeOf((*MockRepository)(nil).DeleteMovieByID), id)
}

// DeleteSessionByID mocks base method.
func (m *MockRepository) DeleteSessionByID(id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionByID", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSessionByID indicates an expected call of DeleteSessionByID.
func (mr *MockRepositoryMockRecorder) DeleteSessionByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionByID", reflect.TypeOf((*MockRepository)(nil).DeleteSessionByID), id)
}

// GetAll mocks base method.
func (m *MockRepository) GetAll() ([]models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepository)(nil).GetAll))
}

// GetAllHalls mocks base method.
func (m *MockRepository) GetAllHalls() ([]models.Hall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHalls")
	ret0, _ := ret[0].([]models.Hall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHalls indicates an expected call of GetAllHalls.
func (mr *MockRepositoryMockRecorder) GetAllHalls() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHalls", reflect.TypeOf((*MockRepository)(nil).GetAllHalls))
}

// GetAllSessions mocks base method.
func (m *MockRepository) GetAllSessions() ([]models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSessions")
	ret0, _ := ret[0].([]models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSessions indicates an expected call of GetAllSessions.
func (mr *MockRepositoryMockRecorder) GetAllSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSessions", reflect.TypeOf((*MockRepository)(nil).GetAllSessions))
}

// GetHallByID mocks base method.
func (m *MockRepository) GetHallByID(id int) (models.Hall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHallByID", id)
	ret0, _ := ret[0].(models.Hall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHallByID indicates an expected call of GetHallByID.
func (mr *MockRepositoryMockRecorder) GetHallByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHallByID", reflect.TypeOf((*MockRepository)(nil).GetHallByID), id)
}

// GetMovieByID mocks base method.
func (m *MockRepository) GetMovieByID(id int) (models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovieByID", id)
	ret0, _ := ret[0].(models.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovieByID indicates an expected call of GetMovieByID.
func (mr *MockRepositoryMockRecorder) GetMovieByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovieByID", reflect.TypeOf((*MockRepository)(nil).GetMovieByID), id)
}

// GetSessionByID mocks base method.
func (m *MockRepository) GetSessionByID(id int) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", id)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockRepositoryMockRecorder) GetSessionByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockRepository)(nil).GetSessionByID), id)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), email)
}

// UpdateHall mocks base method.
func (m *MockRepository) UpdateHall(id int, body models.Hall) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHall", id, body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHall indicates an expected call of UpdateHall.
func (mr *MockRepositoryMockRecorder) UpdateHall(id, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHall", reflect.TypeOf((*MockRepository)(nil).UpdateHall), id, body)
}

// UpdateMovie mocks base method.
func (m *MockRepository) UpdateMovie(id int, body models.Movie) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMovie", id, body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMovie indicates an expected call of UpdateMovie.
func (mr *MockRepositoryMockRecorder) UpdateMovie(id, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMovie", reflect.TypeOf((*MockRepository)(nil).UpdateMovie), id, body)
}

// UpdateSession mocks base method.
func (m *MockRepository) UpdateSession(id int, body models.Session) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", id, body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockRepositoryMockRecorder) UpdateSession(id, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockRepository)(nil).UpdateSession), id, body)
}
