basePath: /cinema-service
definitions:
  models.Hall:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      rows:
        type: integer
      seatsPerRow:
        type: integer
      updatedAt:
        type: string
    type: object
  models.Movie:
    properties:
      created_at:
        type: string
      description:
        type: string
      duration:
        type: integer
      id:
        type: integer
      posterUrl:
        type: string
      title:
        type: string
    type: object
  models.Session:
    properties:
      createdAt:
        type: string
      hallId:
        type: integer
      id:
        type: integer
      movieId:
        type: integer
      price:
        type: number
      startTime:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API для кино-сервиса на Go + Gin + SQLite
  title: Cinema Service API
  version: "1.0"
paths:
  /cinema-service/v1/api/halls:
    get:
      description: Возвращает список всех залов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Hall'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить все залы
      tags:
      - halls
    post:
      consumes:
      - application/json
      description: Добавляет новый зал в систему
      parameters:
      - description: Данные нового зала
        in: body
        name: hall
        required: true
        schema:
          $ref: '#/definitions/models.Hall'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать новый зал
      tags:
      - halls
  /cinema-service/v1/api/halls/{id}:
    delete:
      description: Удаляет зал по его уникальному идентификатору
      parameters:
      - description: ID зала
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить зал по ID
      tags:
      - halls
    get:
      description: Возвращает зал по его уникальному идентификатору
      parameters:
      - description: ID зала
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Hall'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить зал по ID
      tags:
      - halls
    put:
      consumes:
      - application/json
      description: Изменяет данные зала по его идентификатору (доступно только администратору)
      parameters:
      - description: ID пользователя (для проверки прав)
        in: header
        name: user-id
        required: true
        type: string
      - description: ID зала
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные зала
        in: body
        name: hall
        required: true
        schema:
          $ref: '#/definitions/models.Hall'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить зал по ID
      tags:
      - halls
  /cinema-service/v1/api/sessions:
    get:
      description: Возвращает список всех сеансов в системе
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Session'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить все сеансы
      tags:
      - sessions
    post:
      consumes:
      - application/json
      description: Добавляет новый сеанс в систему
      parameters:
      - description: Данные нового сеанса
        in: body
        name: session
        required: true
        schema:
          $ref: '#/definitions/models.Session'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать новый сеанс
      tags:
      - sessions
  /cinema-service/v1/api/sessions/{id}:
    delete:
      description: Удаляет сеанс по его уникальному идентификатору
      parameters:
      - description: ID сеанса
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить сеанс по ID
      tags:
      - sessions
    get:
      description: Возвращает данные сеанса по его уникальному идентификатору
      parameters:
      - description: ID сеанса
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Session'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить сеанс по ID
      tags:
      - sessions
    put:
      consumes:
      - application/json
      description: Изменяет данные сеанса по его идентификатору
      parameters:
      - description: ID сеанса
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные сеанса
        in: body
        name: session
        required: true
        schema:
          $ref: '#/definitions/models.Session'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить сеанс по ID
      tags:
      - sessions
  /movies:
    get:
      description: Возвращает список всех фильмов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Movie'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить все фильмы
      tags:
      - movies
    post:
      description: Создание фильма
      parameters:
      - description: Данные фильма
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/models.Movie'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создание фильма
      tags:
      - movies
  /movies/{id}:
    delete:
      description: Удаление фильма по его ID
      parameters:
      - description: ID фильма
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удаление фильма по ID
      tags:
      - movies
    get:
      description: Возвращает фильм по его ID
      parameters:
      - description: ID фильма
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Movie'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить фильм по ID
      tags:
      - movies
    put:
      description: Обновление фильма по ID
      parameters:
      - description: Данные фильма
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/models.Movie'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновление фильма по ID
      tags:
      - movies
swagger: "2.0"
